flags = -Wall -Werror -Wextra -g -c

ITree = ITree
cola = Cola/cola
intervalos = Intervalos/intervalos
pila = Pila/pila

ITree.o: $(ITree).c $(ITree).h $(pila).h $(intervalos).h $(cola).h
	gcc $(flags) $(ITree).c
